# numPy array operation

In [3]:
import numpy as np

In [11]:
arr = np.arange(12)
print("original array",arr)
print("basics slicing",arr[2:7])
print("with step slicing",arr[2:10:2])
print("negative indexing",arr[-3])

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
basics slicing [2 3 4 5 6]
with step slicing [2 4 6 8]
negative indexing 9


In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("original array\n",arr)
print("specific element",arr[1,2])
print("entire row",arr[1])
print("entire column",arr[:,1])

original array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element 6
entire row [4 5 6]
entire column [2 5 8]


In [ ]:
unsortedArr = np.array([4,2,6,1,3,5])
sortedArr = np.sort(unsortedArr)
print("unsorted array",unsortedArr)
print("sorted array",sortedArr)

unsortedArr_2d = np.array([[4,2,6],[1,3,5]])

unsorted array [4 2 6 1 3 5]
sorted array [1 2 3 4 5 6]
