## importing the numpy

In [1]:
import numpy as np

## creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_1d)
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


array vs list


In [6]:
list = [[1,2,3],[4,5,6]]
arr = np.array(list)

print("list multiplication", list*2)
print("array multiplication", arr*2)


list multiplication [[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
array multiplication [[ 2  4  6]
 [ 8 10 12]]


### to perform the element wise multiplication

In [13]:
list = [1,2,3,4,5]
new_list = [i*2 for i in list]
print("new list",new_list)

new list [2, 4, 6, 8, 10]


### final comparison between array list 

In [21]:
import time

start_time = time.time()

list = [i for i in range(1000000)]
new_list = [i*2 for i in list]
print('time require to to perform the list multiplication',time.time() - start_time)


start_time = time.time()

arr = np.array(list)
new_arr = arr*2
print('time require to to perform the array multiplication',time.time() - start_time)

time require to to perform the list multiplication 0.11458492279052734
time require to to perform the array multiplication 0.0391087532043457


## numpy methods 

In [25]:
a = np.arange(0,20,2)
print(a)

zero = np.zeros((2,3))
print(zero)
ones = np.ones((2,3))
print(ones)


full = np.full((2,3),5)
print(full)


random = np.random.random((2,3))
print(random)

[ 0  2  4  6  8 10 12 14 16 18]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[0.29485735 0.31656954 0.66649625]
 [0.09152994 0.42496229 0.1134094 ]]


## Array properties

In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape",arr.shape)
print("dimension",arr.ndim)
print("size",arr.size)
print("data type",arr.dtype)



shape (2, 3)
dimension 2
size 6
data type int64


## array reshaping

In [ ]:

arr = np.arange(12)
print("original array",arr)

reshaped = arr.reshape(3,4)
print("3 x 4 reshaped array \n",reshaped)

transpose = reshaped.T
print("transposed array\n",transpose)



arr = reshaped.flatten()
print("flattened array",arr)

arr = reshaped.ravel()
print("ravelled array",arr)




original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
3 x 4 reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transposed array
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravelled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


flatten vs revel

In [17]:
a = np.array([[1, 2], [3, 4]])
b = a.flatten()

b[0] = 100
print("Original array:\n", a)  # a is not changed
print("\nFlattened copy:\n", b)


a = np.array([[1, 2], [3, 4]])
b = a.ravel()

b[0] = 100
print("Original array:\n", a)  # a *may* change if b is a view
print("\nRaveled view:\n", b)

Original array:
 [[1 2]
 [3 4]]

Flattened copy:
 [100   2   3   4]
Original array:
 [[100   2]
 [  3   4]]

Raveled view:
 [100   2   3   4]
