In [3]:
import numpy as np

In [2]:
# data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 100, 200, 300, 400],
    [2, 150, 250, 350, 450],
    [3, 200, 300, 400, 500],
    [4, 250, 350, 450, 550],
    [5, 300, 400, 500, 600]
])

print("===== Zomato sales analysis ====")
print("\nsales data shape:", sales_data.shape)
print("\n 1st 3 rows:\n", sales_data[:3])


NameError: name 'np' is not defined

In [39]:
# total scales per year

# total_sales = sales_data.sum(axis=0)
total_sales = np.sum(sales_data[:, 1:], axis=0)
print("\ntotal sales per year:\n", total_sales)

# final = total_sales.sum()
final = np.sum(total_sales)
print("\ntotal sales per restaurant:\n", final)


total sales per year:
 [1000 1500 2000 2500]

total sales per restaurant:
 7000


In [42]:
# minimum sales per shop
min_sales = np.min(sales_data[:, 1:], axis=1)
print("\nminimum sales per year:\n", min_sales)


minimum sales per year:
 [100 150 200 250 300]


In [44]:
# maximum sales per year
max_sales = np.max(sales_data[:, 1:], axis=0)
print("\nmaximum sales per year:\n", max_sales)


maximum sales per year:
 [300 400 500 600]


In [45]:
# avg sales pre shop
avg_sales = np.mean(sales_data[:, 1:], axis=1)
print("\navg sales per year:\n", avg_sales)


avg sales per year:
 [250. 300. 350. 400. 450.]


In [46]:
# cumulative sum
cumulative_sum = np.cumsum(sales_data[:, 1:], axis=1)
print("\ncumulative sum:\n", cumulative_sum)


cumulative sum:
 [[ 100  300  600 1000]
 [ 150  400  750 1200]
 [ 200  500  900 1400]
 [ 250  600 1050 1600]
 [ 300  700 1200 1800]]


In [5]:
shops = ["shop1", "shop2", "shop3", "shop4", "shop5"]

vectorize_upper = np.vectorize(str.upper)

shops = vectorize_upper(shops)
print(shops)

['SHOP1' 'SHOP2' 'SHOP3' 'SHOP4' 'SHOP5']
