# numPy array operation

In [2]:
import numpy as np

In [11]:
arr = np.arange(12)
print("original array",arr)
print("basics slicing",arr[2:7])
print("with step slicing",arr[2:10:2])
print("negative indexing",arr[-3])

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
basics slicing [2 3 4 5 6]
with step slicing [2 4 6 8]
negative indexing 9


In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("original array\n",arr)
print("specific element",arr[1,2])
print("entire row",arr[1])
print("entire column",arr[:,1])

original array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element 6
entire row [4 5 6]
entire column [2 5 8]


In [32]:
# unsortedArr = np.array([4,2,6,1,3,5])
# sortedArr = np.sort(unsortedArr)
# print("unsorted array",unsortedArr)
# print("sorted array",sortedArr)

unsortedArr_2d = np.array([[4,2,6],[1,3,5],[9,8,7]])
row_sortedArr_2d = np.sort(unsortedArr_2d,axis=1)
col_sortedArr_2d = np.sort(unsortedArr_2d,axis=0)
print("unsorted 2d array\n",unsortedArr_2d)
print("\nrow wise sorted 2d array\n",row_sortedArr_2d)
print("\ncolumn wise sorted 2d array\n",col_sortedArr_2d)

unsorted 2d array
 [[4 2 6]
 [1 3 5]
 [9 8 7]]

row wise sorted 2d array
 [[2 4 6]
 [1 3 5]
 [7 8 9]]

column wise sorted 2d array
 [[1 2 5]
 [4 3 6]
 [9 8 7]]


# filtration

In [8]:
arr = np.arange(12)
print("original array",arr)

even_arr = arr[arr%2==0]
print("even number array",even_arr)


m = arr%2==0
print("mask array",m)
print("filtered array",arr[m])

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
even number array [ 0  2  4  6  8 10]
mask array [ True False  True False  True False  True False  True False  True False]
filtered array [ 0  2  4  6  8 10]


fancy indexing and np.where() 

In [48]:
arr = np.arange(12)
print("original array\n",arr)

# idx = [1,4,6,8]
# print("index array\n",idx)

# print("selected element\n",arr[idx])


where_result = np.where(arr%2==0,'X',arr)
print("where result\n",where_result)
# print("selected element\n",arr[where_result])

original array
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
where result
 ['X' '1' 'X' '3' 'X' '5' 'X' '7' 'X' '9' 'X' '11']


### adding and removing data

In [68]:
# arr1 = np.array([1,2,3])
# arr2 = np.array([4,5,6])
# print("adding two array",arr1+arr2)
# print("concatenated array",np.concatenate((arr1,arr2)))

arr_2d = np.array([[1,2,3],[4,5,6]])
new_row = np.array([7,8,9])
new_column = np.array([[7],[8]])

with_new_row = np.vstack((arr_2d,new_row))
print("with new row\n",with_new_row)

with_new_column = np.hstack((arr_2d,new_column))
print("original array\n",arr_2d)
print("with new column\n",with_new_column)

with new row
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
original array
 [[1 2 3]
 [4 5 6]]
with new column
 [[1 2 3 7]
 [4 5 6 8]]


In [ ]:
arr = np.array([[1,2,3, 4,5,6]])
deleted_arr = np.delete(arr,[1,5])
print("deleted column\n",deleted_arr)


# arr = np.array([[1,2,3],[4,5,6]])
# print("original array\n",arr)

# deleted = np.delete(arr,[0,1],axis=0)
# print("deleted row\n",deleted)

# deleted = np.delete(arr,1,axis=1)
# print("deleted column\n",deleted)

AxisError: axis 5 is out of bounds for array of dimension 2